from snakemake.utils import min_version

min_version("9.1.0")

configfile: "config/config.yaml"

groups = ["715932", "823384", "824842", "1906216"]

include: "rules/common.smk"
include: "rules/varpubs.smk"

rule all:
    input:
        expand("results/datavzrd-report/varpubs/{group}.somatic_vus", group=groups),
        lookup(dpath="varpubs/cache", within=config) if lookup(dpath="varpubs/cache", within=config) != "" else []
